### ISSUE TITLE
gcloud info not showing in system report?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/android#157]
I see `  gcloud info --run-diagnostics` in https://github.com/bitrise-docker/android/blob/dfe4ccc498842493a7504a0b783c0d947338df55/system_report.sh#L51

however there's no gcloud here:
https://github.com/bitrise-io/bitrise.io/blob/master/system_reports/linux-docker-android.log

I'd expect the gcloud version info to end up in the system report?

**Comment by bootstraponline** [comment]
The google sdk on bitrise is broken due to https://issuetracker.google.com/issues/73044966 It's fixed in the next sdk release.

https://github.com/travis-ci/travis-ci/issues/9200#issuecomment-364178306

**Comment by viktorbenei** [comment]
Thanks for reporting, update is coming in this weekend's update https://github.com/bitrise-io/bitrise.io/pull/191/files#diff-307894b24f4f586d59bd40b9a0bb4fd3R264

If you have some time feel free to add an additional test to `system_report.sh` to check this issue / to ensure this won't happen again.

**Comment by bootstraponline** [comment]
Is printing gcloud info in `android/system_report.sh` not enough? I thought that'd print the version info into the report.

**Comment by viktorbenei** [comment]
But that was printed correctly with the current version too 😕 -> https://github.com/bitrise-io/bitrise.io/blob/def7e09162a163fe90c7df03153985a3d9d0b16c/system_reports/linux-docker-android.log#L274

**Comment by bootstraponline** [comment]
Oh! I see the issue, it was user error. I searched for `gcloud` but it's called `Google Cloud SDK` in the report.

> Google Cloud SDK 188.0.0

^ that line is what I wanted.

This bug made it through Google's release process, there's not an easy way to test for it. I'd expect it to remain fixed now that they're aware of the issue.

**Comment by bootstraponline** [comment]
```
For this to happen:

1) The server must first be reachable, or reachable at some point in the past. We cache the result of the original check in gcloud's config directory. If the server is always unreachable, we will not attempt to read the default account.
2) Access to the server must then be blocked so the server state no longer matches the cached state
3) No active account is set in the properties (this would probably be common during installation) so we attempt to do the default account lookup (based on the cached state)

If all this happens, then the error will be hit.
```
> https://issuetracker.google.com/issues/73044966#comment7

**Comment by viktorbenei** [comment]
Ahh, that indeed seems like quite a complex bug - thanks for the details @bootstraponline ! ;)
