### ISSUE TITLE
Support official Android testing service by Google

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/android#35]
I'm using the Google cloud SDK to run Android tests on Google's Firebase Test Lab. This is the same testing service that's natively supported in Android Studio.

- https://github.com/instructure/dockerfiles/blob/master/android/Dockerfile

Thoughts on adding the `google-cloud-sdk` command line tool to the Android base image?

**Comment by viktorbenei** [comment]
That's an awesome idea! Feel free to send a PR with the relevant Dockerfile commands.

Note: you can find a guide about how you can use Docker to run your Android/Linux builds locally in the exact same environment what's available on bitrise.io: https://bitrise-io.github.io/devcenter/docker/run-your-build-locally-in-docker/

Note2: if you have a docker image which already has the `google-cloud-sdk`, you can simply `docker run` it from e.g. a `Script` step, just like you would on your own Mac/PC. Related docs: https://bitrise-io.github.io/devcenter/docker/use-your-own-docker-image/#run-docker-commands-during-the-build

That said, the `google-cloud-sdk` is available as an official docker image: https://hub.docker.com/r/google/cloud-sdk/
Due to the frequent updates it might be better to use that, instead of a preinstalled version.
The official image is designed to be easy to use with `docker run` - check the readme on Docker Hub https://hub.docker.com/r/google/cloud-sdk/

**Comment by bootstraponline** [comment]
> Note2: if you have a docker image which already has the google-cloud-sdk, you can simply docker run it from e.g. a Script step, just like you would on your own Mac/PC.

That means I have to wait for the docker image to download on every build. I only have 45m so I'd like to optimize the build times by having the SDK preinstalled.

> Due to the frequent updates it might be better to use that,

The only endpoint I care about (firebase test lab) is rarely updated. For the use case of executing tests, it's not important to always track the latest.

**Comment by viktorbenei** [comment]
Just for reference, I ran a test build with `docker pull google/cloud-sdk`, it takes ~60 seconds, so it might worth to pre install the tools.

But, to preinstall the tools, I'd strongly suggest to use the official Debian / apt install instructions, that's usually the most reliable solution.

**Comment by bootstraponline** [comment]
> I'd strongly suggest to use the official Debian / apt install instructions, that's usually the most reliable solution.

Agreed. The only issue is I don't know what components they're including in that package. I'm testing this now.

**Comment by viktorbenei** [comment]
Let me know how it goes or if you need any help - you can use either our docker image, or the base Ubuntu image for best reproduction

**Comment by bootstraponline** [comment]
I confirmed that the default apt package includes the required components for testing. I'll update the PR to use this instead of wget.
<img width="1022" alt="apt_components" src="https://cloud.githubusercontent.com/assets/1173057/20495591/c30709e0-afef-11e6-9766-4c13f4bc3660.png">

**Comment by viktorbenei** [comment]
Awesome, thank you @bootstraponline !

For reference, this is how we install `gcloud` on bitrise, with a Script step:

```
#!/bin/bash
set -ex
# Create an environment variable for the correct distribution
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
# Add the Cloud SDK distribution URI as a package source
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list
# Import the Google Cloud public key
curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
# Update and install the Cloud SDK
sudo apt-get update && sudo apt-get install -y google-cloud-sdk
# Run gcloud init to get started
# gcloud init
```

**Comment by bootstraponline** [comment]
I was thinking of installing like this:
> sudo apt-get update -qq && \
> sudo apt-get install -y -qq --no-install-recommends google-cloud-sdk

I don't want the extra packages. Individual components can be installed with `gcloud components install ...`

Do you think we should install everything (incl. recommended)?

**Comment by viktorbenei** [comment]
Sure, I'd go with the full `sudo apt-get install -y google-cloud-sdk`, the time it takes doesn't really matter as the docker image is created automatically, once a day, using scheduled builds.

**Comment by viktorbenei** [comment]
Installing all the default components can also help those who want to use other features of the google cloud sdk (like we do ;) )

**Comment by bootstraponline** [comment]
Makes sense. I will update the PR. Thanks for the feedback.

**Comment by idorozenberg** [comment]
Hey,

What happen with this? Is it possible to add Google Test Lab as a step?

**Comment by viktorbenei** [comment]
Sure, or just use a Script step - the google cloud sdk tools are now preinstalled

**Comment by viktorbenei** [comment]
Ahh, @idorozenberg you meant whether we have a step for Google Test Lab (sorry, just read your question again). We don't right now - feel free to create one ;) - but you can use a Script step to use any of the google cloud sdk tools.

**Comment by bootstraponline** [comment]
I'm using the gcloud sdk on bitrise. It's great. 😄 I used a Fastlane script.

**Comment by viktorbenei** [comment]
You should write a quick how-to here http://discuss.bitrise.io/c/how-to @bootstraponline :P

**Comment by bootstraponline** [comment]
My [Fastlane code is open source](https://github.com/instructure/android-uno/blob/8e20a11a2c7e908ab4f31ba1dd7616608d160db3/fastlane/Fastfile#L197) :) I also provided [a bash implementation](https://github.com/bitrise-docker/android/pull/36#issuecomment-262617164).

**Comment by viktorbenei** [comment]
Ahh, you're right, I forgot about that, sorry :)

**Comment by idorozenberg** [comment]
Thank you very much guys! @viktorbenei @bootstraponline

**Comment by idorozenberg** [comment]
Oh @bootstraponline, I found mapbox bitrise yaml that have Firebase Test Cloud implemntation, and also has Firebase result Script step.
[Mapbox bitrise yaml](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/bitrise.yml)

**Comment by viktorbenei** [comment]
Wow, thanks @idorozenberg , I didn't know about that!

**Comment by ido43210** [comment]
Hey, have any of you tried to define the tests using the argfile?
This command keeps failing even though my yaml file is correct:
gcloud beta test android run test.yaml:$ANDROID_ROBO_TEST

And I'm using a bitrise env var inside the yaml. Maybe that is the problem?

Error from gcloud:
ERROR: (gcloud.beta.test.android.run) Error parsing YAML file [test.yaml]: mapping values are not allowed here
  in "test.yaml", line 8, column 7

(Line 8 column 7 has nothing special and this index is always the same no matter if I change the yaml)

**Comment by bootstraponline** [comment]
You're probably using an invalid format. There's gcloud support in the `#test-lab` channel on [Firebase slack](https://firebase.googleblog.com/2016/02/come-join-firebase-slack-community_13.html).

**Comment by idorozenberg** [comment]
Hey.
Yeah. I had a type error in the bash script that causes the yaml to be downloaded badly.
