### ISSUE TITLE
Pre-install packages required for Android Emulator with Google APIs

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-docker/android#4]
How it have to be done today: http://devcenter.bitrise.io/android/android-tips-and-tricks/#emulator-with-google-apis

**Comment by viktorbenei** [comment]
https://gist.github.com/viktorbenei/af51749021ff0525cbbb

**Comment by apacha** [comment]
This would be a great enhancement!

**Comment by koral--** [comment]
I haven't seen this issue before but system image with Google APIs 25 has been added in #68. It was not the objective but simply there is no other image for API 25 (`default` tag is available up to 24).
It should be also no problem to add older images if needed with `sdkmanager "system-images;android-<API level>;google_apis;armeabi-v7a"`.

Additionally, in the meantime start Android emulator step has been also updated: https://github.com/bitrise-steplib/steps-start-android-emulator/pull/32

So there is no need for additional snippets to have runnable emulator with Google APIs.

**Comment by viktorbenei** [comment]
That's true @koral-- I'll go ahead and close this issue for now.

Recommended steps as of today:

- **Install missing Android tools** can detect most of the missing android and build tools packages, so you no longer have to install it with a Script
- **Create Android emulator** can install the required emulator image and related packages, using either `sdkmanager` on the newer stacks, or the old `android sdk update` on the older / LTS stacks (but you don't have to know about this, just set the parameters for the step, it'll call the appropriate tools on the stack)
