### ISSUE TITLE
Possible docker LFS / Dockerfile improvements

### ISSUE THREAD

**Issue by bartimar** [bitrise-docker/android#50]
There is too many layers of the filesystem. Building the image itself takes ages. And it takes too much storage!

This command: 
```
# Cleaning
RUN apt-get clean
```
will only INCREASE the image size and INCREASE the build duration!!! Don't do this!

Look at this please: https://github.com/AckeeCZ/jenkins-android-docker-slave/blob/master/Dockerfile
```
RUN dpkg --add-architecture i386 && \
    apt-get update && \ 
    DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jdk libc6:i386 libstdc++6:i386 libgcc1:i386 libncurses5:i386 libz1:i386 && \
    rm -rf /var/lib/apt/lists/*
```
When I have some time, I could do a MR if you are interested.

**Comment by viktorbenei** [comment]
Thanks for the suggestion and feel free to create a PR/MR!

> There is too many layers of the filesystem. Building the image itself takes ages. And it takes too much storage!

This is true if you only want to build the image once, and never touch it again. Doing things in separate `RUN`s helps with local debugging/development of the image, e.g. when you have to add just one more tool. If we'd have to wait for every package to install again, just because of adding one more package, it'd make it impossible to test changes. I'm also not sure about how much the storage could be shrinked, the Android tools are quite large regardless of how you install them.

**Comment by bartimar** [comment]
Why not using a separate branch/tag for debugging purposes? :) The container for production imho shouldn't suffer just because of the development, testing or debugging. 

I forked the repo, tried just to join the RUN for apt-get and instead of 4GB it shows 3GB now. I didn't check the real size before rounding, but it sure is smaller now :)

I'm not an Android developer, but aren't some of the packages constantly updated, so you'd need to rebuild the whole image again anyway?

**Comment by viktorbenei** [comment]
> I'm not an Android developer, but aren't some of the packages constantly updated, so you'd need to rebuild the whole image again anyway?

Depends. The android packages which include a version number in their name (e.g. `build-tools-25.0.2`) are not updated. But even those which are, you don't always want to re-download every single package, just to test/debug something. Those changes only matter when the production image is created, where the full image is rebuilt every time (it's an automated process).

The main issue with installing all packages in one `RUN` is that sometimes packages can't be downloaded / the download fail. It's better now than it was in the past, but this can still happen. In this case, if you do a single RUN and the last package download fails, you have to download the whole list again, which is a real PITA and time consuming.

I'm not against changing the structure, but only if that makes any use case easier / better. Right now the most common use case is core developers working on this `Dockerfile`, and pretty much everyone else just uses the published docker images, 99%+ on bitrise.io where it's pre-cached and doesn't need to be downloaded.

**Comment by viktorbenei** [comment]
One more note: to remove intermediate containers you can use the `--force-rm` flag of `docker build`.
