### ISSUE TITLE
Unnecessary huge image due to doing `rm` wrong

### ISSUE THREAD

**Issue by williamchong007** [bitrise-docker/android#71]
In a Dockerfile, `rm`ing in a separate `RUN` will not decrease the image size.
As each `RUN` creates a new image layer, `rm` only "hides" the files from later layer, the resulting image will still contain those files, thus very huge.

example:
```
RUN cd /opt && wget -q https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O android-sdk.tgz
RUN cd /opt && tar -xvzf android-sdk.tgz
RUN cd /opt && rm -f android-sdk.tgz
```
should be instead 
```
RUN cd /opt && wget -q https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz -O android-sdk.tgz && tar -xvzf android-sdk.tgz && rm -f android-sdk.tgz
```
for the `rm` to be actually meaningful

Extra read, section `Clean up right away`:
https://blog.codeship.com/reduce-docker-image-size/

**Comment by viktorbenei** [comment]
Good point - feel free to send a PR!

**Comment by williamchong007** [comment]
In fact all images under this account suffer the same problems too, just saying

**Comment by viktorbenei** [comment]
Feel free to send us PRs! ;)

P.S.: since Docker 1.13 (?) you can run `docker build` with `--squash` to discard intermediate layers - https://docs.docker.com/engine/reference/commandline/build/#squash-an-images-layers---squash-experimental-only

**Comment by viktorbenei** [comment]
Closing as this is no longer the case.

If you'd have any further improvement idea feel free to create a new issue.

Thanks for the ticket & discussion @williamchong007 ! ;)
