### ISSUE TITLE
Preinstall AWS CLI?

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/android#92]
Thoughts on preinstalling the Amazon CLI?

- https://aws.amazon.com/cli/

This is useful for syncing artifacts to S3.

> pip install awscli

**Comment by viktorbenei** [comment]
I'm not sure about this one, AFAIK the `awscli` changes quite frequently, so doing `pip install awscli` during the build seems to be a better solution.

Additional note: awscli is also available as an `apt` package, so `apt-get install awscli` should also work, no need for `pip`

**Comment by bootstraponline** [comment]
apt version of pip is a bit old.

> 1.10.1-1
> https://packages.ubuntu.com/xenial/awscli

on github, they're up to:

> 1.11.117
> https://github.com/aws/aws-cli/blob/master/CHANGELOG.rst

> awscli changes quite frequently

That's true. The core commands (S3 sync) are stable though. I see this as similar to the gcloud CLI. There are a lot of changes however the most frequently used commands don't break.

I think for the `Ubuntu 16.04` stack, it makes sense to have support for scripting S3 out of the box.
