### ISSUE TITLE
Preinstall pip

### ISSUE THREAD

**Issue by bootstraponline** [bitrise-docker/android#93]
> pip: command not found

pip is popular for installing Python apps (such as the AWS CLI)

```
sudo apt-get install -y python-dev
wget https://bootstrap.pypa.io/get-pip.py
python get-pip.py
```

**Comment by viktorbenei** [comment]
Wouldn't mind it, if it conforms to https://github.com/bitrise-io/osx-box-bootstrap/blob/master/PULL_REQUEST_TEMPLATE.md feel free to send a PR! ;)

**Comment by viktorbenei** [comment]
Just a note, `python-pip` is available in `apt`. In one of our projects we do:

```
sudo apt-get install -y python-pip python-dev build-essential
```

that should be enough for PIP

**Comment by viktorbenei** [comment]
That said, I'd rather have this in the base docker image (https://github.com/bitrise-docker/bitrise-base), as this is not android related

**Comment by bootstraponline** [comment]
Ok, I'll move it over there.
